### ISSUE TITLE
init() issue

### ISSUE THREAD

**Issue by juxton** [rorygarand/react-amplitude#14]
I've noticed that supplying a callback to the init() method never fires. Diggin in further, I see src/index.js init calls:

amplitude.getInstance().init(apiKey, userId, config, cb);

However, looking at dist/index.js init call shows:

amplitude.getInstance().init(apiKey);

Is dist/index.js building correctly? Is it up to date?

**Comment by rorygarand** [comment]
Hi @juxton, sorry for taking so long to respond. I'm seeing the same thing locally with the build I sent to npm.

Thanks for reporting this, I'm not sure why it wasn't built properly.

Should be fixed in [0.1.6](https://github.com/rorygarand/react-amplitude/releases/tag/0.1.6)
