### ISSUE TITLE
amplitude undefined error

### ISSUE THREAD

**Issue by astevens1** [rorygarand/react-amplitude#15]
Hi! I'm trying to use this module, and running into a few issues. This seems to be part of my problem:

https://github.com/rorygarand/react-amplitude/blob/7ad84d2c2e7b20d159800651546a0498dc354870/src/index.js#L41

statement doesn't do anything. Here's example code:

```javascript
var obj = {};

if (!'foo' in obj) {
  console.log("foo not found");
} else {
  console.log ("Foo found");
  var a = !'foo';
  console.log("A: " + a);
}
// Result:
// Foo found
// A: false
//
// The result is you are looking for false in obj
```

**Comment by rorygarand** [comment]
Hmm, ok. I'll put in a different check and push it up in just a bit.

**Comment by rorygarand** [comment]
Should be good here: https://github.com/rorygarand/react-amplitude/releases/tag/0.1.7

I'm pushing to npm now, please let me know if this doesn't address the problem.
