### ISSUE TITLE
Update Amplitude API Version

### ISSUE THREAD

**Issue by kijun** [rorygarand/react-amplitude#2]
Do you have plans to update it? The latest library is on 3.4.1.

**Comment by rorygarand** [comment]
Sure thing. Can you wait until tomorrow?

If you can't wait, submit a PR with a fix and I'll get it merged in.

**Comment by Gp2mv3** [comment]
Is it updated ?

**Comment by rorygarand** [comment]
almost. i need to make a couple of additional checks then publish to npm.
