### ISSUE TITLE
AmplitudeClient is not defined webpack error after v0.1.0 update

### ISSUE THREAD

**Issue by chasedut** [rorygarand/react-amplitude#5]
Installed the latest v0.1.0 and there is a webpack error.

Might AmplitudeClient need to be imported/defined? Src below:

<img width="1119" alt="screen shot 2018-01-30 at 10 11 10 am" src="https://user-images.githubusercontent.com/13496464/35583250-24dfc424-05a6-11e8-9b21-f7bbbb2e1005.png">

**Comment by rorygarand** [comment]
Ah, I see the problem. I'll patch and get an update shortly.

**Comment by rorygarand** [comment]
Ok, should be fixed in: https://github.com/rorygarand/react-amplitude/releases/tag/0.1.1.

I also published to npm.

Let me know if there are any further problems.

**Comment by chasedut** [comment]
Thanks! v0.1.1 is looking good so far!! Appreciate your collaboration :-) 👍
